SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess Off

SecAuditEngine RelevantOnly
SecAuditLog /var/log/modsec_audit.log
SecAuditLogParts ABIJDEFHZ

SecDebugLog /var/log/modsec_debug.log
SecDebugLogLevel 0

SecResponseBodyMimeType text/plain text/html text/xml application/json
SecDataDir /var/cache/modsecurity